### ISSUE TITLE
Cases could be constants for better readability

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#1]
https://github.com/Sosa09/QuizMaker/blob/ce71fef087791bcc256e46fb0175a7003a14fb2a/QuizMaker/Program.cs#L45-L58

You can declare the cases as constants in order to make the code more readable. When reading "0" for example is not that easy to understand what is the mode, you have to rely on the method that is invoked in that case. So declare some constants with proper namees to describe the modes.

**Comment by Sosa09** [comment]
![image](https://github.com/user-attachments/assets/0859b961-7390-4708-b39e-b937ad4f4779)
 That was a bit stupid of me had to think about it
