### ISSUE TITLE
how about creating a validation method?

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#11]
https://github.com/Sosa09/QuizMaker/blob/dd14ca44728f635716f1257a765cee63c696a269/QuizMaker/Program.cs#L31-L39

Both of those blocks are just validating user's choice for the menu. Maybe a method that will contain both blocks can be added here to make the code a bit easier to read? This method could be also used inside HandlePlayQuizMenu cause there's some duplicated code in there doing the same kind of validations if I am not mistaken

**Comment by Sosa09** [comment]
You are totally right done this is done now
