### ISSUE TITLE
Method name not matching with what this method is doing

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#2]
https://github.com/Sosa09/QuizMaker/blob/ce71fef087791bcc256e46fb0175a7003a14fb2a/QuizMaker/FileHandler.cs#L54-L63

This method's name is suggesting that it's going to read from a file. So what we expect when we see it is to parse the file (after checking for it's existance) and return back a list with questions/answers if exists. But it returns back a StreamReader object which is going to be null if the file does not exist.

That's kind of a trouble. 

Maybe this method is better to parse the file and return it back. 

It also requires some proper error handling as it's not working if there's no file because the reader is going to be null

**Comment by Sosa09** [comment]
REnamed it but also refactored to handle the xml parsing directly by integratyion <T> so i can pass the type i want to parse and return xml to text

Now i have to rework on or let's say refactor profilehandoler and DataHandler that get these textstream with proper methods
