### ISSUE TITLE
Is loading (or creating a quiz) a good idea here?

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#3]
https://github.com/Sosa09/QuizMaker/blob/ce71fef087791bcc256e46fb0175a7003a14fb2a/QuizMaker/Program.cs#L30-L35

I mean, the user might not even want to play the quiz at this point. Maybe the user selects immediately to create a quiz. But you are loading a quiz that already exists (if exists) and In my opinion this is a waste of resources since the user might not even use it.

**Comment by Sosa09** [comment]
i mean it is just checking if there are questions in the system so in case that the player wants to play he ahs some questions otherwise it's mandatory to create some before even entering the main menu.
that was the idea behind this.

but nevermind i will remove it 💯
