### ISSUE TITLE
Magic number alert :)

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#4]
https://github.com/Sosa09/QuizMaker/blob/ce71fef087791bcc256e46fb0175a7003a14fb2a/QuizMaker/QuizLogic.cs#L89

That 5000 makes no sence here. Declare a constant for it and use the constant instead

**Comment by Sosa09** [comment]
I really need to double check my code after a nap and not after i done programming this will help me detect or think about this :)
