### ISSUE TITLE
Those properties can also be readonly

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#5]
https://github.com/Sosa09/QuizMaker/blob/ce71fef087791bcc256e46fb0175a7003a14fb2a/QuizMaker/QuizLogic.cs#L5-L7

readonly keyword is used to declare fields in a class that can only be assigned values during their initialization. it is useful when you want to define fields whose values should be set during object initialization and should not change for the lifetime of the object. 

Improves maintainability and code performance

**Comment by Sosa09** [comment]
Perfect just learned something new :) i knew about the readonly but never thought about using it always thought it wasn't thatr useful

These are objects that cannot be set a constants right ? because of their mutability ? or am i totally wrong here (did not searched) i was just guessing
