### ISSUE TITLE
name needs a bit of work

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/QuizMaker#7]
https://github.com/Sosa09/QuizMaker/blob/c74c6546034a75e068c7adb5be3a851940ea8484/QuizMaker/QuizLogic.cs#L119

This method name contains no verbs at all so it needs a verb in the name to explain the context of the method, essentially point to the action that this method takes. A good practice on bool methods is to use is or has as the verb, so this method can be renamed to IsProfileListEmpty 

Same thing applies to method of the UserInterface **MandatoryProfileCreactionText**. There's no verb in it.

**Comment by Sosa09** [comment]
TYhanks for the advice for the bool i will write it down !

Renamed MandatoryProfileCreactionText to DisplayQuestionsNotFoundMessage()
and the bool to IsProfileListEmpty
